### ISSUE TITLE
Offscreen rendering

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#19]
I was wondering if the igx charts have the possibility of utilizing the new OffscreenCanvas, or if there are any plans to do so? https://developers.google.com/web/updates/2018/08/offscreen-canvas 

If the load of a chart is too heavy, sometimes charts causes the browser to freeze while rendering. It would be great to render such charts in its own thread (web worker)

**Comment by gmurray81** [comment]
This is a possibility. However, in practice our goal is just to render so quickly for as many scenarios as possible that this shouldn't be necessary.

If you need to take the render workflow to a different thread, chances are this is because it is taking you more than 16ms to render.

Being able to take that to a different thread is great.... but.... if you are taking that long to render, that means you can't actually sustain 60hz updates.

So, while we could do this work, generally the time is better spent in identifying a scenario where the render is taking longer than 16ms to do, and optimizing that scenario, rather than to push the render workflow to a different thread.

The main area where the render happening on a different thread would help is if the main UI thread has a lot of OTHER work going on, and so is messing with the chart performance, or vice versa.

Rendering offscreen has better applications for when you know you are going to be rendering something _expensive_ that will definitely take longer than a handful of milliseconds, so you need to take it off the UI thread to avoid blocking. This is why we render the HeatMap content in a worker thread, since it is exactly that scenario.

However, since the goal of everything in the chart is to render in a handful of milliseconds so as to maintain as high a framerate as possible, rendering off-thread is of dubious utility. I'm unaware of the exact implementation details for every browser, but you are likely paying some small marshaling or at least locking overhead when blitting the Offscreen canvas on the main thread from the other thread. It may be that this overhead cancels out any gain you would have accrued by shifting the work.

Certainly this request is highly feasible, since we could probably add an option to run the logic core of the chart in a worker, and have the API shell on the main thread, marshaling things across, however, its still a bunch of investment that would be likely better spent addressing any scenario that doesn't run at 60fps, instead.

**Comment by gmurray81** [comment]
additionally, AFAIK, OffscreenCanvas isn't supported in IE or Safari, so this would be a bunch of investment that only benefits some of the browsers, rather than investment that benefits all of them today, by tuning a scenario that isn't running at 60fps.

Note, with HeatMap, due to the lack of universal support for OffscreenCanvas, we actually generate the raw pixel data offthread, and then marshal it to the UIthread for blitting. This is feasible for HeatMap since its a per-pixel accumulation. But wouldn't work especially well for more traditional 2D painting.

**Comment by gmurray81** [comment]
BTW, @Eralmidia if you have a scenario that was problematic and causing UI locking definitely let me know, as we should tune it.

**Comment by Eralmidia** [comment]
@gmurray81 Thanks for the detailed reply. First just a quick disclaimer: Our company have used Infragistics components for many years now, both ASP, igniteui and now the Angular components. We are in the process of converting our solution to Angular, but as of yet, we haven't converted any module with charts. We will however start the process of converting a large reporting module this year, which has a lot of charts. So I will be looking into the charting module very soon, but as of now, my experience is mainly for the jquery igniteui based components. Do you consider the Angular charts to be more efficient than the old igniteui ones?

As for performance, for most charts, I agree that it shouldn't be needed. However, for example, one of the reports we provide for our customers, are based on data they generate from a third party testing software. Each report consist on x number of "steps" in the testing process, and in theory, each of these steps can have a chart. Without any charts, this report generally render in about a second. But if there are a lot of charts, it could easily take upwards of 10 seconds. Having the ability to show the report just as quickly as one without charts, and just insert the charts as they become available, seems like a good idea in theory.

But to be honest, this was more of a query than a feature request. Obviously, you are the charting expert, so it may very well be that, as you say, the overhead of handling a worker thread isn't even worth it.

**Comment by Eralmidia** [comment]
Also, when I got your attention: the older feature requests, from last year. Are any of them planned or in progress by any chance? As I said, we will be using the charts quite a bit going forward, and some of those things would be wonderful to have available 😉

**Comment by gmurray81** [comment]
There are some increased efficiencies in the Angular/React version of the charts, but theres a lot of similarity to the core, so an issue that may have existed for ignite, could potentially exist here too. Do you have any example data you could share with us to and we can see if there is something we could tune for your scenario?

Scatter line is inherently less performant than a regular line series, since there is less that we can assume about the shape of the data (its allowed to backtrack on itself, etc.) 

One thing I would suggest, is that if you don't actually need scatter line, to use line instead, since it establishes more constraints on the data that allow it to perform better from a rendering standpoint. For example, just because you have numeric values for x, or date values for x, doesn't, in itself, necessitate using a numeric x axis. The one constraint that the category x axis imposes is that the data will be treated as equally spaced along the axis, rather than a larger numeric gap, or date gap, being rendered as so. If you can accept that constraint, then those constraints are also what can help us render the shape more efficiently.

Now, if those constraints don't fit, then that doesn't help, of course, but likely there's still something we could do to help with more info about the data.

If the scenario is extreme enough of course (tons of data, series, and charts) then even tuning might not help create an optimal experience, and it may be appropriate to be able to take things "offline" as it were.

An interesting idea that perhaps you could consider, if the scenario is extreme enough, is that you can actually render our chart [on the server](https://www.infragistics.com/community/blogs/b/engineering/posts/using-node-js-to-show-our-jquery-chart-in-older-browsers) and embed an image in the page. And swap to an interactive version only when someone attempts to interact with the component. I'd want to make sure we couldn't help the scenario run more efficiently before going to that kind of length, though.

**Comment by gmurray81** [comment]
as to the other features, some of those you can do in app code at present. Would a sample help? But I don't think they are currently highly prioritized in terms of adding as features, so may be later than sooner in terms of built in, although you could contact our product management to get more info (and put in a vote)

The dash array support, though, will be coming reasonably soon, I think.

**Comment by Eralmidia** [comment]
Well, it's not really a large issue for us at present. It was really more of an inquiry to whether this could be a possible performance improvement to test.

I'll leave it to you to close this issue, if this feature isn't worth looking into 😉

Having some samples on some of the other feature requests would be great. It's not really a high priority to have it built in, as long as it's possible.
