### ISSUE TITLE
Is there a way to set title for Igx-doughnut-charts? 

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular-charts#29]
## Question  
Is there a way to specify a title for a igx-doughnut chart? It would be nice to be able to add a title describing the doughnut chart data. The title could for instance be in the center of the doughnut chart. 

See picture for context
![image](https://user-images.githubusercontent.com/43247999/70128383-faefd980-167c-11ea-8955-0d794b70fcc1.png)

 * igniteui-angular version: 
 * browser:

**Comment by kdinev** [comment]
Moving the issue to the repository for the charts.

**Comment by agoldenbaum** [comment]
Hello VirtualisProject,

Thank you for your post!

Unfortunately, the igx-doughnut-chart does not currently have a title or a built-in way to put content in the center or at the top of the ring. For the time being, I would recommend utilizing a <label> object to achieve this.

If you would like to see title functionality potentially implemented for the igx-doughnut-chart component, I would recommend suggesting a new product idea for this at the Infragistics' Ignite UI for Angular Ideas Site, here: https://www.infragistics.com/community/ideas/i/ignite-ui-for-angular. Please note that in order to post here, you will need an Infragistics account if you do not have one already, but this will place you in direct communication with our product management teams who plan and prioritize upcoming features and development based on community and user feedback.

Sincerely,
Andrew Goldenbaum
Software Developer
Infragistics

**Comment by VirtualisProject** [comment]
Thanks for getting back to me so quickly @agoldenbaum. 

Alright, i'll visit the product idea center and suggest the feature there.
