### ISSUE TITLE
Stacked bar charts does not render series

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular-charts#39]
I cannot get any stacked bar charts to work, not even the examples on your page. see link:
https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos-dv/charts/data-chart-type-stacked-column-series?file=src%2Fapp%2Fdata-chart-type-stacked-column-series%2Fdata-chart-type-stacked-column-series.component.html

**Comment by gmurray81** [comment]
Hi,
This is actually due to a missing module when that sample comes up in Stackblitz, I've fixed it in this forked sample:

https://stackblitz.com/edit/github-exckfz?file=src/app/app.module.ts

You basically just need to add `IgxDataChartStackedModule` to the imports of the app module.

@HUSSAR-mtrela could you look into why this doesn't get added to the imports for Stackblitz, please?
