### ISSUE TITLE
Labels not rendering

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#46]
Are there any inputs to the chart or axis which controls when to render labels? I have the following chart:
![image](https://user-images.githubusercontent.com/12936286/124115304-edbfea00-da6d-11eb-8440-ffd646a6b1ca.png)

Seems to me that there should be more than enough space for the chart to show all labels here, not every other one.

**Comment by agoldenbaum** [comment]
Hi Eralmidia,

From your screenshot, I am unsure if you are using the IgxCategoryChart or the IgxDataChart, but I will address both scenarios below.

If you are using the IgxDataChart, you can set the "interval" property on the CategoryXAxis to 1 in order to have all labels drawn. The interval property determines the frequency that labels are drawn on the axis.

If you are using the IgxCategoryChart, you can set the xAxisInterval property to 1 instead.

Please let me know if you have any other questions or concerns on this matter.

Sincerely,
Andrew Goldenbaum
Software Developer - Team Lead
Infragistics

**Comment by Eralmidia** [comment]
Unfortunately, doing this seems to make the chart rendering itself constantly. I think there might be an issue with setting the gap and having a 45 degree angle on the labels. 

Don't know if it's a bug in our current version of the grid. I'll test it again once we get a chance to upgrade from Angular 10.
