### ISSUE TITLE
Vertical line-series in composite data-chart

### ISSUE THREAD

**Issue by Jelnes** [IgniteUI/igniteui-angular-charts#48]
Hello, 

I have a data chart with a series of bar-series and would like to add vertical line-series. Is this possible, and do you have any examples on how to do this?

**Comment by agoldenbaum** [comment]
Hi Jelnes,

Thank you for your post!

The best thing I can recommend for a vertical line series when plotting a bar chart in the IgxDataChart is to use the Value Overlay feature of the chart. You can read about the Value Overlay in our documentation, here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/charts/features/chart-overlays.

The example given in the documentation uses a Column series, but the same idea applies for the Bar series. If you set the axis of the IgxValueOverlay to your numeric X-Axis when plotting your Bar series, you can plot a vertical line that way.

Please let me know if you have any other questions or concerns on this matter.

Sincerely,
Andrew Goldenbaum
Software Developer – Team Lead
Infragistics

**Comment by Jelnes** [comment]
Hello Agoldenbaum, 

This is not quite solving my problem, as it seems the value overlay displays a line at a single numeric value. 

Is there any way to create a vertical line that is bound to a datasource and e.g. displays the change of a value over time in a vertical matter, similar to what the line-series does horizontally?

**Comment by agoldenbaum** [comment]
Hello Jelnes,

My apologies, I had misunderstood what you were looking for – I was under the impression you were simply looking for a vertical line.

Unfortunately, the IgxDataChart does not expose a built-in line series that can use the CategoryYAxis as its category axis and plot data vertically. The built-in category line series can only plot data horizontally at this time. With that said, something you might be able to do in this case is to plot your data as an IgxColumnSeries and an IgxLineSeries using the IgxCategoryXAxis. Then, using some transform CSS on the div container of the chart, you could rotate the chart 90 degrees, giving it a visualization of a bar-series rather than a column series. The IgxCategoryXAxis has a labelAngle property you can then set in order to rotate the labels back so that they look more like the IgxCategoryYAxis does.

If you would like to see a line series potentially exposed in a future version, I would recommend suggesting a new product idea for this at our Ignite UI for Angular Ideas Site, here: https://www.infragistics.com/community/ideas/i/ignite-ui-for-angular. This will place you in direct communication with our product management teams who plan and prioritize upcoming features and development based on community feedback.

Please let me know if you have any other questions or concerns on this matter.

Sincerely,
Andrew Goldenbaum
Software Developer – Team Lead
Infragistics
